# url: http://localhost:1313
baseURL: "https://egyutt-ertuk.hu"
name: Együtt-Értük Alapítvány
title: Együtt-Értük Alapítvány
module:
  imports:
    - path: github.com/privatemaker/headless-cms
theme: meghna-hugo
defaultContentLanguage: hu
taxonomies:
  palyazat: palyazatok
  tag: tags
params:
  darkModeToggle: true
  enableSearch: true
  logo: images/logo.png
  favicon: images/favicon.png
  google_analytics_id: G-0846F6GREM

  social:
    - icon: fa fa-facebook-f fa-brands
      link: https://www.facebook.com/EgyuttErtukAlapitvany
    - icon: fa fa-youtube fa-brands
      link: https://www.youtube.com/@egyutt-ertuk

  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: https://fonts.googleapis.com/css?family=Montserrat|Anaheim|Quattrocento+Sans:400,700&display=swap
      - link: plugins/fontawesome/css/all.css
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  headless_cms:
    engine: "sveltia"
    site_url: "https://egyutt-ertuk.hu"
    backend:
      name: "github"
      repo: "egyutt-ertuk-hu/egyutt-ertuk-hu.github.io"
    collections:
      palyazatok:
        name: palyazatok
        create: true
        folder: "content/palyazatok"
        path: "{{id}}/_index"
        fields:
          - { name: title, label: Title }
          - { name: id, label: ID }
          - {
              name: logo,
              label: Logo,
              widget: select,
              options: [nea-logo, eta-logo],
            }
          - { name: body, label: Body, widget: markdown }

      blog:
        name: blog
        create: true
        folder: "content/blog"
        path: "{{date}}-{{slug}}/index"
        fields:
          - { name: title, label: Title }
          - { name: date, label: Date, widget: datetime, type: date }
          - {
              name: tags,
              label: "Vezércikk? (igen/nem)",
              widget: select,
              options: ["vezércikk"],
              multiple: true,
              required: false,
            }
          - {
              name: palyazatok,
              label: Pályázatok,
              widget: relation,
              collection: palyazatok,
              multiple: true,
            }
          - { name: body, label: Body, widget: markdown }
          - {
              name: cover,
              label: Cover Image,
              widget: image,
              multiple: false,
              pattern: "cover.*",
            }

outputs:
  home:
    - HTML
    - AMP
    - RSS
    - HeadlessCMSConfig
  # - JSON
searchKeys:
  - "tags"
  - "date"
  - "categories"
  - "summary"
  - "content"
  - "link"
  - "author"

menu:
  main:
    - name: Kezdőlap
      url: ""
      weight: 1
    - name: Tevékenységeink
      url: "#about"
      weight: 2
    - name: Hírek
      url: "#blog"
      weight: 3
    - name: Rólunk
      url: "/rolunk"
      weight: 4
    - name: Támogatóink
      url: "#team"
      weight: 5
    - name: Támogatás
      url: "#donate"
      weight: 6
ignoreLogs:
  - "warning-goldmark-raw-html"
