url: http://localhost:1313
name: Együtt-Értük Alapítvány
title: Együtt-Értük Alapítvány
theme: meghna-hugo
defaultContentLanguage: hu
taxonomies:
  palyazat: palyazatok
params:
  darkModeToggle: true
  enableSearch: true
  logo: images/logo.png
  favicon: images/favicon.png

  homepage:
    social:
      # Global params common for both languages
      title: "Közösségi média"
      description: "Kövess minket!"
      icons:
        - website: facebook
        - url: https://www.facebook.com/EgyuttErtukAlapitvany

  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: https://fonts.googleapis.com/css?family=Montserrat|Anaheim|Quattrocento+Sans:400,700&display=swap
      - link: plugins/fontawesome/css/all.css
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
outputs:
  home:
  - HTML
  - AMP
  - RSS
  # - JSON
searchKeys:
  - "tags"
  - "date"
  - "categories"
  - "summary"
  - "content"
  - "link"
  - "author"
  
menu:
  main:
    - name: Kezdőlap
      url: ''
      weight: 1
    - name: Tevékenységeink
      url: '#about'
      weight: 2
    - name: Hírek
      url: '#blog'
      weight: 3
    - name: Rólunk
      url: '/rolunk'
      weight: 4
    - name: Támogatóink
      url: '#team'
      weight: 5
    - name: Támogatás
      url: '#donate'
      weight: 6
