url: http://localhost:1313
name: Együtt-Értük Alapítvány
title: Együtt-Értük Alapítvány
theme: blist
defaultContentLanguage: hu
params:
  darkModeToggle: true
  enableSearch: true
  logo: images/logo.png
  favicon: images/favicon.png

  homepage:
    social:
      # Global params common for both languages
      title: "Közösségi média"
      description: "Kövess minket!"
      icons:
        - website: facebook
        - url: https://www.facebook.com/EgyuttErtukAlapitvany

outputs:
  home:
  - HTML
  - AMP
  - RSS
  - JSON
searchKeys:
  - "tags"
  - "date"
  - "categories"
  - "summary"
  - "content"
  - "link"
  - "author"
  
menu:
  main:
    - name: Kezdőlap
      url: '/'
      weight: 1
    - name: Rólunk
      url: '/rolunk'
      weight: 2
    - name: Tevékenységeink
      url: '/tevekenysegeink'
      weight: 3
    - name: Archívum
      url: '/archivum'
      weight: 4
    - name: Támogatás
      url: '/tamogatas'
      weight: 5
