url: http://localhost:1313
name: Együtt-Értük Alapítvány
title: Együtt-Értük Alapítvány
theme: ananke
defaultContentLanguage: hu

menu:
  main:
    - name: Kezdőlap
      url: '/'
      weight: 1
    - name: Rólunk
      url: '/rolunk'
      weight: 2
    - name: Tevékenységeink
      url: '/tevekenysegeink'
      weight: 3
    - name: Archívum
      url: '/archivum'
      weight: 4
    - name: Támogatás
      url: '/tamogatas'
      weight: 5
